import { type NextPage } from "next";
import Link from "next/link";
import Head from "next/head";

export default function Layout({ children }: { children: JSX.Element }) {
  return (
    <>
      <Head>
        <title>Family Video App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1>Family Video App</h1>
        <nav>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/tape">Tape</Link>
            </li>
          </ul>
        </nav>
        {children}
      </main>
    </>
  );
}
